spring:
  application:
    name: employee-task-assessment

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/task_db}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890123456789012345678901234567890}
  expiration: ${JWT_EXPIRATION:3000000}
